# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CIMON@home
email: herwig@cimonathome.de
description: >- # this means to ignore newlines until "baseurl:"
  CIMON is the first AI powered astronaut assistant currently being tested on the Internation Space Station (ISS) by ISS Commander Alexander Gerst.
  CIMON was developed by Airbus and ESA and is heavily using cloud services for speech to text and text to speech as well as cognitive applications.
  These cloud services are also available to everybody so essentially you can build your CIMON at home.
baseurl: "cimonathome" # the subpath of your site, e.g. /blog
url: "https://hdiessner.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SternwarteF
github_username:  hdiessner@gmx.net

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
        layout: "post"
        categories: cimon update

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
